// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.Extensions.DependencyInjection;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Tasks.Application.Migrations
{
    [DbContext(typeof(DefaultTaskDbContext))]
    [Migration("20210315211011_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("task")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Tasks.Model.Domain.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int4")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("AssignedIdNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_id_number");

                    b.Property<bool>("Completed")
                        .HasColumnType("bool")
                        .HasColumnName("completed");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("EstimatedRequiredHours")
                        .HasColumnType("int4")
                        .HasColumnName("estimated_required_hours");

                    b.Property<string>("MinimumRoles")
                        .HasColumnType("text")
                        .HasColumnName("minimum_roles");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentTaskId")
                        .HasColumnType("int4")
                        .HasColumnName("parent_task_id");

                    b.Property<string>("Stack")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("stack");

                    b.HasKey("Id")
                        .HasName("pk_task_task_id");

                    b.HasIndex("ParentTaskId");

                    b.ToTable("task");
                });

            modelBuilder.Entity("Tasks.Model.Domain.Task", b =>
                {
                    b.HasOne("Tasks.Model.Domain.Task", "ParentTask")
                        .WithMany("LinkedTasks")
                        .HasForeignKey("ParentTaskId");

                    b.Navigation("ParentTask");
                });

            modelBuilder.Entity("Tasks.Model.Domain.Task", b =>
                {
                    b.Navigation("LinkedTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
